### ISSUE TITLE
Doesn't work on Django 1.9?

### ISSUE THREAD

**Issue by gluzio** [runekaagaard/django-admin-flexselect#9]
This doesn't work on Django 1.9 - is there another way to do this now?

error: ImportError: cannot import name execute_manager

**Comment by runekaagaard** [comment]
Closing this ancient issue. We actually have it running in Django 3.2 vendored and are willing to create a new release if there is still interest, though probably not at this point.
